name: Vite Client CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'client/**'

jobs:
  build-client:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Vite app
        run: npm run build

      - name: Run tests
        run: npm test || echo "No tests found"

      # Optional: Upload build artifacts
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: vite-build
          path: client/dist
